services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Brightside\Paginatedprocessors\DataProcessing\PaginatedDatabaseQueryProcessor:
    public: true
  Brightside\Paginatedprocessors\DataProcessing\PaginatedMenuProcessor:
    public: true
  Brightside\Paginatedprocessors\DataProcessing\PaginatedFilesProcessor:
    public: true
